# -*- coding: utf-8 -*-
"""kadai_015.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wm_WDSxvMXqCj_kCcpJVYpj2QYBH0mGP
"""

class Human:
  def __init__(self):
    self.name = ""
  def set_nameage(self, name, age):
    self.name = name
    self.age = age
  def printinfo(self):
    print(self.name, self.age)

myAccount = Human()
myAccount.set_nameage("侍太郎", 30)

myAccount.printinfo()