# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uhRJ7wv3q6qO96UlPME-CU9dmiND6Baz
"""

top_bar = 10
under_bar = 20
height = 5

print(str((top_bar + under_bar) * height / 2) + "㎠" )