# -*- coding: utf-8 -*-
"""kadai_017.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UFMXFe6Qwn4EVE2SxV15g3UJabrdEG7S
"""

# Humanクラスの定義
class Human:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  def check_adult(self):
    if self.age >= 20:
      print ("大人です")
    else:
      print("大人ではありません")

# インスタンス化
user1 = Human("侍太郎", 25)
user2 = Human("侍次郎", 19)
user3 = Human("侍三郎", 10)

# リスト化
lists = [user1, user2, user3]

# ループ処理
for i in range(0, 3):
  lists[i].check_adult()