# -*- coding: utf-8 -*-
"""kadai_011.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yLcsAhZnvdoQZ-00cI38DdOJOci7q9wD
"""

list = ["水","金","地","火","木","土","天","海","冥"]

for i in range(0,9):
  print(list[i])

i = 0
while i < 9:
  print(list[i])
  i = i + 1